### PR TITLE
Fix instrumentation test

### PR DESCRIPTION
**Pull request by mir47**
- Add `testInstrumentationRunner` to build.gradle
- Add `runBlocking` to test that calls suspend function

### CODE REVIEW

**Comment by Dannark** [comment]
It did fix my problem too! All tests passed well now.

**Comment by sebastienrussell** [comment]
Same here, Thanks @mir47 for the fix.

**Comment by SudKul** [comment]
Thanks, @mir47 for suggesting the fix.

**Comment by marcoongithubnow** [comment]
Thanks! now it works.

**Comment by HAYASAKA-Ryosuke** [comment]
Thanks. The test is now running.

**Pull request merged**
